FROM openjdk:11
WORKDIR /code
RUN apt-get update && apt-get install -y curl zip unzip && \
    curl -s https://get.sdkman.io | bash && \
    bash -c "source $HOME/.sdkman/bin/sdkman-init.sh && sdk install kotlin" && \
    echo "source $HOME/.sdkman/bin/sdkman-init.sh" >> $HOME/.bashrc && \
    rm -rf /var/lib/apt/lists/*
ENV PATH="/root/.sdkman/candidates/kotlin/current/bin:$PATH"
CMD ["sh", "-c", "kotlinc /code/main.kt -include-runtime -d /code/main.jar && java -jar /code/main.jar"]